version: '3.4'
services:
    postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRESS_PASSWORD=admin1234
            - POSTGRES_DB=carsDb
        ports:
            - "5432:5432"
        restart: always
        volumns:
            -   database-data:/var/lib/postgressql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - "5050:80"
        restart: always
        volumns:
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
    pgadmin: